name: 打包msykanswer.py为exe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: 安装python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 安装requirements.txt
        run: pip install -r requirements.txt

      - name: 安装pyinstaller
        run: pip install pyinstaller

      - name: 打包单文件exe并移动至根目录
        run: |
          pyinstaller -F ./msykanswer.py
          move ./dist/msykanswer.exe ./

      - name: 自动生成更新文档
        run: write-output "CHANGELOG:${{ github.event.head_commit.message }}" | out-file -filepath ./CHANGELOG.txt
        
      - name: 上传Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./msykanswer.exe"
          tag: ver-${{ github.sha }}
          bodyFile: "./CHANGELOG.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
